### ISSUE TITLE
Logging in with non defined user makes an uncatched error

### ISSUE THREAD

**Issue by uldics** [Diyzzuf/grav-plugin-private#27]
For example I have multiple pages, one of them blog, which is private. When it is clicked on, username and password is asked. If I enter a username and password defined in /var/www/grav/user/config/plugins//var/www/grav/user/config/plugins all is ok, user gets in. But when entering undefined user, any combination, then user gets an error visible in browser and it gets logged as:
`
[2017-05-26 19:52:38] grav.CRITICAL: Undefined index: wootwoot - Trace: #0 /var/www/grav/user/plugins/private/private.php(224): Whoops\Run->handleError(8, 'Undefined index...', '/var/www/grav/u...', 224, Array) #1 /var/www/grav/user/plugins/private/private.php(167): Grav\Plugin\PrivatePlugin->sendLogin() #2 /var/www/grav/user/plugins/private/private.php(126): Grav\Plugin\PrivatePlugin->getLoginPage() #3 [internal function]: Grav\Plugin\PrivatePlugin->onPageInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #4 /var/www/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #5 /var/www/grav/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #6 /var/www/grav/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #7 /var/www/grav/system/src/Grav/Common/Grav.php(277): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #8 /var/www/grav/system/src/Grav/Common/Processors/PagesProcessor.php(25): Grav\Common\Grav->fireEvent('onPageInitializ...') #9 /var/www/grav/system/src/Grav/Common/Grav.php(126): Grav\Common\Processors\PagesProcessor->process() #10 /var/www/grav/system/src/Grav/Common/Grav.php(368): Grav\Common\Grav->Grav\Common\{closure}() #11 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #12 /var/www/grav/system/src/Grav/Common/Grav.php(344): call_user_func_array(Object(Closure), Array) #13 /var/www/grav/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->__call('measureTime', Array) #14 /var/www/grav/index.php(52): Grav\Common\Grav->process() #15 {main} [] []
`

private.yaml has following start, the rest is default:

```
enabled: true
routes:
  login: /login
  logout: /logout
session_ss: apache_fastcgi
private_site: false
private_tag: hidden
enable_username: true
users:
  testuser: 6aed8f69402c1d7e81aff1bb2fd59d48e9b7639c
texts:
  h1: 'Private Area'
  h2: 'Please <strong>login</strong> to view this content...'

```

First I thought I have missed some config etc., but I cant find any, looks like a bug.

**Comment by Diyzzuf** [comment]
Config is good...
I don't find any where the error can come.. I have tested with your parameters and everything is functional.
Try to reinstall the plugin.

**Comment by uldics** [comment]
Does not help. I also suspect some config problems in login, error or adminpanel plugins, but I can't see anything related.
Could it be that I only have one file for my only admin account in /var/www/grav/user/accounts and no testuser.yaml in there? But it shouldn't affect some third random logonname attempt.

**Comment by Diyzzuf** [comment]
Sorry I didn't understand the "undefined" user.

Fixed in New Release.
Or just update your private.php file, line 223/224
